services:
  springapp:
    build: .
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/bankapi?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
    ports:
      - '8080:8080'